### GET request with a header
GET http://localhost:8080/api/student
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api/student
Content-Type: application/json

{
  "id": 10,
  "name": "C",
  "faculty" : {
    "id": 1
  }
}

### Send POST request with json body
PATCH http://localhost:8080/api/student/update/3
Content-Type: application/json

{
  "name": "V"
}




